[tool.poetry]
name = "scraper"
version = "0.1.0"
description = ""
authors = ["NielsenErik <eriknielsen98@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
